name: build-image

on:
  push:
    branches:
      - dev

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v4
    
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v3

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Login to DockerHub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
        
        - name: Build and Push Docker image
          uses: docker/build-push-action@v5
          with:
            context: ./portfolio
            file: ./portfolio/Dockerfile
            platforms: linux/amd64
            push: true
            tags: ${{ secrets.DOCKER_USERNAME }}/portfolio:latest
        
        - name: Setup SSH Key
          run: |
            mkdir -p ~/.ssh
            echo "${{ secrets.AWS_SSH_KEY }}" > ~/.ssh/ssh_key.pem
            chmod 400 ~/.ssh/ssh_key.pem
            ssh-keyscan -H ${{ secrets.AWS_HOST }} >> ~/.ssh/known_hosts
        
        - name: Run Docker container on AWS EC2
          run: |
            ssh -o StrictHostKeyChecking=no -i ~/.ssh/ssh_key.pem ${{ secrets.AWS_USER }}@${{ secrets.AWS_HOST }} "
            docker pull ${{ secrets.DOCKER_USERNAME }}/portfolio:latest;
            docker ps -q --filter ancestor=${{ secrets.DOCKER_USERNAME }}/portfolio:latest | xargs -r docker stop;
            docker ps -a -q --filter ancestor=${{ secrets.DOCKER_USERNAME }}/portfolio:latest | xargs -r docker rm;
            docker run -d -p 80:3000 ${{ secrets.DOCKER_USERNAME }}/portfolio:latest"