name: build-image

on:
  push:
    branches:
      - dev

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v4
    
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v3

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Login to DockerHub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
        
        - name: Build and Push Docker image
          uses: docker/build-push-action@v5
          with:
            context: ./portfolio
            file: ./portfolio/Dockerfile
            platforms: linux/amd64
            push: true
            tags: ${{ secrets.DOCKER_USERNAME }}/portfolio:latest
        
        - name: Run Docker image on AWS EC2
          uses: appleboy/ssh-action@v1.2.0
          with:
            host: ${{ secrets.AWS_HOST }}
            username: ${{ secrets.AWS_USER }}
            key: ${{ secrets.AWS_SSH_KEY }}
            script: |
              docker pull ${{ secrets.DOCKER_USERNAME }}/portfolio:latest
              docker run -d -p 80:3000 ${{ secrets.DOCKER_USERNAME }}/portfolio:latest